name change (read comments)
1) had to change the name from Grid to Cells cause:
"error CS0542: 'Grid': member names cannot be the same as their enclosing type"

2) check line 11:
Collection initialization can be simplified (IDE0300)
Avoid unnecessary zero-length array allocations. Use Array.Empty<uint>() instead. (CA1825).
Grid.cs(11, 17): Collection initialization can be simplified